// This script downloaded from www.JavaScriptBank.com
/**
 * @author bhussain
 */
<!--
function time(fieldId){
var str='';
str+='\n'+'<!DOCTYPE HTML PUBLIC "-\/\/W3C\/\/DTD HTML 4.01\/\/EN" "http:\/\/www.w3.org\/TR\/html4\/strict.dtd">';
str+='\n'+'<html>';
str+='\n'+'	<head>';
str+='\n'+'		<meta http-equiv="Content-Type" content="text\/html; charset=iso-8859-1" \/>';
str+='\n'+'		<title>Untitled Document<\/title>';
str+='\n'+'		<script language="JavaScript">';
str+='\n'+'			<!--';
str+='\n'+'			function inc(id,max){';
str+='\n'+'				try{';
str+='\n'+'					var elemenet = document.getElementById(id);';
str+='\n'+'					if(parseInt(elemenet.value) >= parseInt(max)){';
str+='\n'+'						elemenet.value = "00";';
str+='\n'+'						return;';
str+='\n'+'					}';
str+='\n'+'					if (elemenet.value.length == 0){';
str+='\n'+'						elemenet.value = "00";';
str+='\n'+'					}else if(elemenet.value.length == 1){';
str+='\n'+'						elemenet.value = "0" + elemenet.value;';
str+='\n'+'					}';
str+='\n'+'					var tens = elemenet.value.substring(0,1);';
str+='\n'+'					var ones = elemenet.value.substring(1,2);';
str+='\n'+'					if(parseInt(ones)<9){';
str+='\n'+'						ones = parseInt(ones) + 1;					';
str+='\n'+'					}else{';
str+='\n'+'						tens = parseInt(tens) + 1;	';
str+='\n'+'						ones = "0";				';
str+='\n'+'					}';
str+='\n'+'					elemenet.value = tens + ones;';
str+='\n'+'				}catch(e){';
str+='\n'+'					alert("insert numbers in : " + id);';
str+='\n'+'				}';
str+='\n'+'			}';
str+='\n'+'			function dec(id,max){';
str+='\n'+'				try{';
str+='\n'+'					var elemenet = document.getElementById(id);';
str+='\n'+'					if(elemenet.value == "0" || elemenet.value == "00"){';
str+='\n'+'						elemenet.value = max;';
str+='\n'+'						return;';
str+='\n'+'					}';
str+='\n'+'					if (elemenet.value.length == 0){';
str+='\n'+'						elemenet.value = "00";';
str+='\n'+'					}else if(elemenet.value.length == 1){';
str+='\n'+'						elemenet.value = "0" + elemenet.value;';
str+='\n'+'					}';
str+='\n'+'					var tens = elemenet.value.substring(0,1);';
str+='\n'+'					var ones = elemenet.value.substring(1,2);';
str+='\n'+'					if(parseInt(ones)> 0){';
str+='\n'+'						ones = parseInt(ones) - 1;					';
str+='\n'+'					}else{';
str+='\n'+'						tens = parseInt(tens) - 1;	';
str+='\n'+'						ones = "9";				';
str+='\n'+'					}';
str+='\n'+'					elemenet.value = tens + ones;';
str+='\n'+'				}catch(e){';
str+='\n'+'					alert("insert numbers in : " + id);';
str+='\n'+'				}';
str+='\n'+'			}';
str+='\n'+'			function setValue(){';
str+='\n'+'				var hourElement = document.getElementById("hour");';
str+='\n'+'				var minElement = document.getElementById("min");';
str+='\n'+'				var secElement = document.getElementById("sec");';
str+='\n'+'				var ampmElement = document.getElementById("ampm");';
str+='\n'+'				var timeElement = document.getElementById("time");';
str+='\n'+'				timeElement.value = hourElement.value+":"+minElement.value';
str+='\n'+'									+":"+secElement.value+" "+ampmElement.value;';
str+='\n'+'				opener.document.getElementById("'+fieldId+'").value=timeElement.value';
str+='\n'+'			}';
str+='\n'+'			function parseTime(){';
str+='\n'+'				try{';
str+='\n'+'					var hourElement = document.getElementById("hour");';
str+='\n'+'					var minElement = document.getElementById("min");';
str+='\n'+'					var secElement = document.getElementById("sec");';
str+='\n'+'					var ampmElement = document.getElementById("ampm");';
str+='\n'+'					var timeElement = document.getElementById("time");';
str+='\n'+'					var elements = timeElement.value.split(":");';
str+='\n'+'					elements[2]=elements[2].substr(0,2);		';
str+='\n'+'					for (i = 0; i < elements.length; i++) {';
str+='\n'+'						if (isNaN(elements[i])) {';
str+='\n'+'							throw Error;';
str+='\n'+'						}';
str+='\n'+'					}';
str+='\n'+'					hourElement.value = elements[0];';
str+='\n'+'					minElement.value = elements[1];';
str+='\n'+'					secElement.value = elements[2];';
str+='\n'+'					if(	timeElement.value.match("AM")!= null';
str+='\n'+'						||timeElement.value.match("am")!= null){';
str+='\n'+'						ampmElement.value = "AM";	';
str+='\n'+'					}else{';
str+='\n'+'						ampmElement.value = "PM";';
str+='\n'+'					}';
str+='\n'+'				}catch(e){';
str+='\n'+'					alert("insert value in correct format for ex: " + "01:25:09 AM");';
str+='\n'+'				}';
str+='\n'+'				';
str+='\n'+'			}';
str+='\n'+'			function validateTime(id,max){';
str+='\n'+'				try{';
str+='\n'+'					var elemenet = document.getElementById(id);';
str+='\n'+'					if(isNaN(elemenet.value)){';
str+='\n'+'						element.value="00";';
str+='\n'+'						throw Error;';
str+='\n'+'					}';
str+='\n'+'					if(parseInt(elemenet.value)>parseInt(max)){';
str+='\n'+'						alert("value of "+id+" must be less than "+max);';
str+='\n'+'						element.value="00";';
str+='\n'+'					}';
str+='\n'+'				}catch(e){';
str+='\n'+'					alert("insert numbers in : " + id);';
str+='\n'+'					document.getElementById(id).value = "00";';
str+='\n'+'				}';
str+='\n'+'			}';
str+='\n'+'			\/\/-->';
str+='\n'+'		<\/script>';
str+='\n'+'	<\/head>';
str+='\n'+'	<body>';
str+='\n'+'		<form name="timeForm">';
str+='\n'+'		<table border=1>';
str+='\n'+'			<tr>';
str+='\n'+'				<td>';
str+='\n'+'					<input id="hour" type="text" maxlength="2" size="2" value="00" onblur="validateTime(\'hour\',12);"\/>';
str+='\n'+'				<\/td>';
str+='\n'+'				<td>';
str+='\n'+'					<table >';
str+='\n'+'						<tr valign="bottom">';
str+='\n'+'							<td>';
str+='\n'+'								<img src="up.jpg" onclick="inc(\'hour\',12);">';
str+='\n'+'							<\/td>';
str+='\n'+'						<\/tr>';
str+='\n'+'						<tr valign="top">';
str+='\n'+'							<td>';
str+='\n'+'								<img src="down.jpg" onclick="dec(\'hour\',12);">';
str+='\n'+'							<\/td>';
str+='\n'+'						<\/tr>';
str+='\n'+'					<\/table>';
str+='\n'+'				<\/td>';
str+='\n'+'					<td>';
str+='\n'+'						<input id="min" type="text" maxlength="2" size="2" value="00" onblur="validateTime(\'min\',59);"\/>';
str+='\n'+'					<\/td>';
str+='\n'+'				<td>';
str+='\n'+'					<table>';
str+='\n'+'						<tr>';
str+='\n'+'							<td>';
str+='\n'+'								<img src="up.jpg" onclick="inc(\'min\',59);">';
str+='\n'+'							<\/td>';
str+='\n'+'						<\/tr>';
str+='\n'+'						<tr>';
str+='\n'+'							<td>';
str+='\n'+'								<img src="down.jpg" onclick="dec(\'min\',59);">';
str+='\n'+'							<\/td>';
str+='\n'+'						<\/tr>';
str+='\n'+'					<\/table>';
str+='\n'+'				<\/td>';
str+='\n'+'					<td>';
str+='\n'+'						<input id="sec" type="text" maxlength="2" size="2" value="00" onblur="validateTime(\'sec\',59);"\/>';
str+='\n'+'					<\/td>';
str+='\n'+'				<td>';
str+='\n'+'					<table>';
str+='\n'+'						<tr>';
str+='\n'+'							<td>';
str+='\n'+'								<img src="up.jpg" onclick="inc(\'sec\',59);">';
str+='\n'+'							<\/td>';
str+='\n'+'						<\/tr>';
str+='\n'+'						<tr>';
str+='\n'+'							<td>';
str+='\n'+'								<img src="down.jpg" onclick="dec(\'sec\',59);">';
str+='\n'+'							<\/td>';
str+='\n'+'						<\/tr>';
str+='\n'+'					<\/table>';
str+='\n'+'				<\/td>';
str+='\n'+'				<td>';
str+='\n'+'					<select id="ampm">';
str+='\n'+'						<option value="AM" selected="selected">AM<\/option>';
str+='\n'+'						<option value="PM">PM<\/option>';
str+='\n'+'					<\/select>';
str+='\n'+'				<\/td>';
str+='\n'+'			<\/tr>';
str+='\n'+'			<tr>';
str+='\n'+'				<td colspan="7">';
str+='\n'+'					<input type="button" value="Go!" onclick="setValue();"\/>';
str+='\n'+'					<input type="text" id="time"\/>		';
str+='\n'+'					<input type="button" value="Parse" onclick="parseTime();"\/>			';
str+='\n'+'				<\/td>';
str+='\n'+'			<\/tr>';
str+='\n'+'		<\/table>';
str+='\n'+'		<\/form>';
str+='\n'+'	<\/body>';
str+='\n'+'<\/html>';
win = window.open("","TimePicker","toolbar=0,status=0,titlebar=0,toolbar=0,menubar=0,fullscreen=no,width=320,height=110,resizable=0,scrollbars=0");
doc= win.document;
doc.open();
doc.write(str);
}
//-->